const $ = (s) => document.querySelector(s);
const state = { token: sessionStorage.getItem('ilink_admin_token') || '', view: 'overview', cache: {} };
const titles = {
  overview: ['Overview','Ringkasan sistem iLink'], transactions:['Transaksi','Kelola transaksi dan status order'], users:['Pengguna','Data pengguna Telegram'],
  products:['Produk','Persiapan katalog untuk marketplace berikutnya'], redeem:['Redeem','Buat dan kelola kode redeem'], broadcast:['Broadcast','Kirim pesan melalui bot Telegram'],
  backups:['Backup','Database SQLite dan backup lokal'], settings:['Pengaturan','Pengaturan non-rahasia aplikasi'], system:['Sistem & Audit','Status runtime, integrasi, dan aktivitas admin']
};

function esc(v=''){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function rupiah(v){return 'Rp '+Number(v||0).toLocaleString('id-ID');}
function date(v){if(!v)return '-';try{return new Date(v).toLocaleString('id-ID');}catch{return String(v)}}
function bytes(v){const n=Number(v||0);if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(1)+' MB';}
function badge(status){const s=String(status||'').toLowerCase();const cls=['completed','paid','success','active','running'].includes(s)?'ok':['pending','inactive'].includes(s)?'warn':['failed','blocked','cancelled'].includes(s)?'bad':'';return `<span class="badge ${cls}">${esc(status||'-')}</span>`}
function toast(msg,bad=false){const t=$('#toast');t.textContent=msg;t.className='toast show'+(bad?' bad':'');clearTimeout(toast._t);toast._t=setTimeout(()=>t.className='toast',2600)}

async function api(path, options={}){
  const qs = '/api/gateway?path='+encodeURIComponent(path);
  const headers = {...(options.headers||{})};
  if(state.token) headers.authorization='Bearer '+state.token;
  if(options.body && typeof options.body !== 'string' && !(options.body instanceof Blob)){headers['content-type']='application/json';options.body=JSON.stringify(options.body)}
  const res=await fetch(qs,{...options,headers});
  const ct=res.headers.get('content-type')||'';
  if(options.raw){ if(!res.ok) throw new Error(`HTTP ${res.status}`); return res; }
  const data=ct.includes('json')?await res.json():{ok:res.ok,message:await res.text()};
  if(res.status===401){logout(false);throw new Error('Sesi berakhir. Silakan login lagi.');}
  if(!res.ok||data.ok===false) throw new Error(data.message||data.error||`HTTP ${res.status}`);
  return data;
}

function showLogin(){ $('#loginView').classList.remove('hidden');$('#appView').classList.add('hidden'); }
function showApp(){ $('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden'); }
function logout(msg=true){state.token='';sessionStorage.removeItem('ilink_admin_token');showLogin();if(msg)toast('Sesi ditutup');}

$('#loginForm').addEventListener('submit',async(e)=>{e.preventDefault();$('#loginError').textContent='';try{
  const r=await api('/api/admin/auth/login',{method:'POST',body:{username:$('#loginUsername').value,password:$('#loginPassword').value}});
  state.token=r.token;sessionStorage.setItem('ilink_admin_token',r.token);$('#loginPassword').value='';showApp();await navigate('overview');
}catch(err){$('#loginError').textContent=err.message;}});
$('#logoutBtn').addEventListener('click',()=>logout());
$('#refreshBtn').addEventListener('click',()=>navigate(state.view,true));
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)navigate(b.dataset.view)});

async function navigate(view,force=false){state.view=view;document.querySelectorAll('#nav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
  const [title,sub]=titles[view]||[view,''];$('#pageTitle').textContent=title;$('#pageSubtitle').textContent=sub;$('#content').innerHTML='<div class="card"><div class="empty">Memuat...</div></div>';
  try{await ({overview:loadOverview,transactions:loadTransactions,users:loadUsers,products:loadProducts,redeem:loadRedeem,broadcast:loadBroadcast,backups:loadBackups,settings:loadSettings,system:loadSystem}[view]||loadOverview)();}catch(err){$('#content').innerHTML=`<div class="card"><div class="empty">${esc(err.message)}</div></div>`;toast(err.message,true)}}

async function loadOverview(){const r=await api('/api/admin/overview');const s=r.stats||{};const bot=r.bot||{};setBot(bot);
$('#content').innerHTML=`<div class="stats-grid">
${stat('Total Pengguna',s.users,'Aktif '+(s.active_users||0))}${stat('Total Transaksi',s.transactions,'Pending '+(s.pending_transactions||0))}${stat('Omzet',rupiah(s.revenue),'Hari ini '+rupiah(s.today_revenue))}${stat('Profit',rupiah(s.profit),'Hari ini '+rupiah(s.today_profit))}
${stat('Produk',s.products,'Aktif '+(s.active_products||0))}${stat('DB SQLite',bytes(s.db_size_bytes),'Lokal Pterodactyl')}${stat('Transaksi Hari Ini',s.today_transactions,'Realtime dari SQLite')}${stat('Bot Telegram',bot.running?'Online':'Offline',bot.username?'@'+bot.username:'Belum dikonfigurasi')}
</div><div class="card"><div class="card-head"><h3>Build Admin-Only</h3></div><div class="card-body"><div class="section-note">Marketplace sengaja belum disertakan. Produk tetap dapat dikelola agar database siap ketika marketplace ditambahkan nanti. Telegram menggunakan long polling sehingga bot tidak memerlukan webhook.</div></div></div>`}
function stat(label,value,small){return `<div class="stat-card"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(small||'')}</small></div>`}
function setBot(bot){const on=!!bot.running;$('#botDot').className='dot '+(on?'ok':'bad');$('#botStatus').textContent=on?(bot.username?'@'+bot.username:'Bot online'):'Bot offline'}

async function loadTransactions(){const r=await api('/api/admin/transactions?limit=250');state.cache.transactions=r.items||[];
$('#content').innerHTML=`${toolbar('Cari transaksi...','trxSearch','Tambah Transaksi','addTrx')}<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Order</th><th>Pembeli</th><th>Produk</th><th>Qty</th><th>Jumlah</th><th>Profit</th><th>Status</th><th>Waktu</th><th></th></tr></thead><tbody id="trxRows">${trxRows(state.cache.transactions)}</tbody></table></div></div>`;
$('#trxSearch').oninput=e=>$('#trxRows').innerHTML=trxRows(filterRows(state.cache.transactions,e.target.value,['order_ref','telegram_id','buyer_name','product_name']));$('#addTrx').onclick=()=>openTransaction();bindTableActions();}
function trxRows(rows){return rows.length?rows.map(x=>`<tr><td class="mono">${esc(x.order_ref)}</td><td>${esc(x.buyer_name||x.telegram_id||'-')}</td><td>${esc(x.product_name||'-')}</td><td>${x.qty}</td><td>${rupiah(x.amount)}</td><td>${rupiah(x.profit)}</td><td>${badge(x.status)}</td><td>${date(x.created_at)}</td><td><div class="actions"><button class="btn small" data-edit-trx="${x.id}">Edit</button><button class="btn small danger" data-del-trx="${x.id}">Hapus</button></div></td></tr>`).join(''):`<tr><td colspan="9" class="empty">Belum ada transaksi</td></tr>`}

async function loadUsers(){const r=await api('/api/admin/users?limit=500');state.cache.users=r.items||[];
$('#content').innerHTML=`${toolbar('Cari ID / username...','userSearch','','')}<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Telegram ID</th><th>Username</th><th>Nama</th><th>Saldo</th><th>Status</th><th>Terakhir aktif</th><th></th></tr></thead><tbody id="userRows">${userRows(state.cache.users)}</tbody></table></div></div>`;
$('#userSearch').oninput=e=>$('#userRows').innerHTML=userRows(filterRows(state.cache.users,e.target.value,['telegram_id','username','first_name']));bindTableActions();}
function userRows(rows){return rows.length?rows.map(x=>`<tr><td class="mono">${esc(x.telegram_id)}</td><td>${x.username?'@'+esc(x.username):'-'}</td><td>${esc([x.first_name,x.last_name].filter(Boolean).join(' ')||'-')}</td><td>${rupiah(x.balance)}</td><td>${badge(x.status)}</td><td>${date(x.last_seen_at)}</td><td><div class="actions"><button class="btn small" data-edit-user="${esc(x.telegram_id)}">Edit</button><button class="btn small danger" data-del-user="${esc(x.telegram_id)}">Hapus</button></div></td></tr>`).join(''):`<tr><td colspan="7" class="empty">Belum ada pengguna</td></tr>`}

async function loadProducts(){const r=await api('/api/admin/products?limit=500');state.cache.products=r.items||[];
$('#content').innerHTML=`${toolbar('Cari produk...','productSearch','Tambah Produk','addProduct')}<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Kode</th><th>Produk</th><th>Kategori</th><th>Harga</th><th>Modal</th><th>Stok</th><th>Status</th><th></th></tr></thead><tbody id="productRows">${productRows(state.cache.products)}</tbody></table></div></div>`;
$('#productSearch').oninput=e=>$('#productRows').innerHTML=productRows(filterRows(state.cache.products,e.target.value,['code','name','category']));$('#addProduct').onclick=()=>openProduct();bindTableActions();}
function productRows(rows){return rows.length?rows.map(x=>`<tr><td class="mono">${esc(x.code)}</td><td>${esc(x.name)}</td><td>${esc(x.category||'-')}</td><td>${rupiah(x.price)}</td><td>${rupiah(x.cost)}</td><td>${x.stock}</td><td>${badge(x.active?'active':'inactive')}</td><td><div class="actions"><button class="btn small" data-edit-product="${x.id}">Edit</button><button class="btn small danger" data-del-product="${x.id}">Hapus</button></div></td></tr>`).join(''):`<tr><td colspan="8" class="empty">Belum ada produk</td></tr>`}

async function loadRedeem(){const r=await api('/api/admin/redeem?limit=500');state.cache.redeem=r.items||[];
$('#content').innerHTML=`${toolbar('Cari kode...','redeemSearch','Buat Redeem','addRedeem')}<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Kode</th><th>Tipe</th><th>Nilai</th><th>Status</th><th>Diklaim Oleh</th><th>Expired</th><th></th></tr></thead><tbody id="redeemRows">${redeemRows(state.cache.redeem)}</tbody></table></div></div>`;
$('#redeemSearch').oninput=e=>$('#redeemRows').innerHTML=redeemRows(filterRows(state.cache.redeem,e.target.value,['code','claimed_by']));$('#addRedeem').onclick=openRedeem;bindTableActions();}
function redeemRows(rows){return rows.length?rows.map(x=>`<tr><td class="mono">${esc(x.code)}</td><td>${esc(x.type)}</td><td>${rupiah(x.value)}</td><td>${badge(x.active?'active':'inactive')}</td><td>${esc(x.claimed_by||'-')}</td><td>${date(x.expires_at)}</td><td><div class="actions"><button class="btn small" data-toggle-redeem="${x.id}" data-active="${x.active}">${x.active?'Nonaktifkan':'Aktifkan'}</button><button class="btn small danger" data-del-redeem="${x.id}">Hapus</button></div></td></tr>`).join(''):`<tr><td colspan="7" class="empty">Belum ada kode redeem</td></tr>`}

async function loadBroadcast(){const r=await api('/api/admin/broadcasts?limit=50');
$('#content').innerHTML=`<div class="card"><div class="card-head"><h3>Kirim Broadcast</h3></div><div class="card-body"><div class="form-grid"><label class="full">Pesan<textarea id="broadcastMessage" placeholder="Tulis pesan broadcast..."></textarea></label><div><button id="sendBroadcast" class="btn primary">Kirim ke Pengguna</button></div></div></div></div><div class="card"><div class="card-head"><h3>Riwayat</h3></div><div class="table-wrap"><table class="table"><thead><tr><th>Waktu</th><th>Pesan</th><th>Total</th><th>Terkirim</th><th>Gagal</th></tr></thead><tbody>${(r.items||[]).map(x=>`<tr><td>${date(x.created_at)}</td><td>${esc(String(x.message).slice(0,80))}</td><td>${x.total}</td><td>${x.sent}</td><td>${x.failed}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Belum ada broadcast</td></tr>'}</tbody></table></div></div>`;
$('#sendBroadcast').onclick=async()=>{const m=$('#broadcastMessage').value.trim();if(!m)return toast('Pesan masih kosong',true);if(!confirm('Kirim pesan ini ke semua pengguna aktif?'))return;const b=$('#sendBroadcast');b.disabled=true;b.textContent='Memulai...';try{const x=await api('/api/admin/broadcast',{method:'POST',body:{message:m}});toast('Broadcast dimulai di VPS');b.textContent='Mengirim di background...';await pollBroadcast(x.job.id,b)}catch(e){toast(e.message,true);b.disabled=false;b.textContent='Kirim ke Pengguna'}}}

async function pollBroadcast(jobId,button){for(let i=0;i<180;i++){await new Promise(r=>setTimeout(r,2000));try{const x=await api(`/api/admin/broadcast/status?job_id=${encodeURIComponent(jobId)}`);const j=x.job;button.textContent=`Mengirim ${j.sent}/${Math.max(j.total,j.sent+j.failed)}`;if(j.status==='completed'){toast(`Broadcast selesai: ${j.sent} terkirim, ${j.failed} gagal`);button.disabled=false;button.textContent='Kirim ke Pengguna';await loadBroadcast();return}if(j.status==='failed'){throw new Error(j.error||'Broadcast gagal')}}catch(e){button.disabled=false;button.textContent='Kirim ke Pengguna';toast(e.message,true);return}}button.disabled=false;button.textContent='Kirim ke Pengguna';toast('Broadcast masih berjalan di VPS. Refresh riwayat beberapa saat lagi.')}

async function loadBackups(){const r=await api('/api/admin/backups');
$('#content').innerHTML=`<div class="card"><div class="card-head"><h3>Backup SQLite</h3><button id="createBackup" class="btn primary">Buat Backup Sekarang</button></div><div class="card-body"><div class="section-note">Backup disimpan di folder <span class="mono">data/backups</span> pada Pterodactyl. Restore dilakukan saat server berhenti dengan mengganti file database utama.</div></div><div class="table-wrap"><table class="table"><thead><tr><th>File</th><th>Ukuran</th><th>Waktu</th><th></th></tr></thead><tbody>${(r.items||[]).map(x=>`<tr><td class="mono">${esc(x.name)}</td><td>${bytes(x.size_bytes)}</td><td>${date(x.created_at)}</td><td><div class="actions"><button class="btn small" data-download-backup="${esc(x.name)}">Download</button><button class="btn small danger" data-del-backup="${esc(x.name)}">Hapus</button></div></td></tr>`).join('')||'<tr><td colspan="4" class="empty">Belum ada backup</td></tr>'}</tbody></table></div></div>`;
$('#createBackup').onclick=async()=>{try{await api('/api/admin/backups',{method:'POST',body:{}});toast('Backup berhasil dibuat');loadBackups()}catch(e){toast(e.message,true)}};bindTableActions();}

async function loadSettings(){const r=await api('/api/admin/settings');const s=r.settings||{};
$('#content').innerHTML=`<div class="card"><div class="card-head"><h3>Pengaturan Umum</h3></div><div class="card-body"><form id="settingsForm" class="form-grid"><label>Nama Store<input name="store_name" value="${esc(s.store_name||'iLink Store')}" /></label><label>Timezone<input name="timezone" value="${esc(s.timezone||'Asia/Jakarta')}" /></label><label>Currency<input name="currency" value="${esc(s.currency||'IDR')}" /></label><label>Maintenance<select name="maintenance_mode"><option value="true" ${s.maintenance_mode?'selected':''}>Aktif</option><option value="false" ${!s.maintenance_mode?'selected':''}>Nonaktif</option></select></label><label class="full">Catatan Dashboard<textarea name="dashboard_note">${esc(s.dashboard_note||'')}</textarea></label><div><button class="btn primary" type="submit">Simpan Pengaturan</button></div></form></div></div>`;
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);const body=Object.fromEntries(fd.entries());body.maintenance_mode=body.maintenance_mode==='true';try{await api('/api/admin/settings',{method:'PATCH',body});toast('Pengaturan disimpan')}catch(err){toast(err.message,true)}}}

async function loadSystem(){const [sys,audit]=await Promise.all([api('/api/admin/system'),api('/api/admin/audit?limit=100')]);setBot(sys.integrations?.telegram||{});
const i=sys.integrations||{};$('#content').innerHTML=`<div class="kv-grid">${kv('Node.js',sys.node)}${kv('Uptime',Math.floor((sys.uptime_seconds||0)/60)+' menit')}${kv('Database',sys.database?.engine+' / '+sys.database?.file)}${kv('Backup',sys.database?.backups+' file')}${kv('Telegram',i.telegram?.configured?(i.telegram.running?'Online':'Configured / Offline'):'Belum diisi')}${kv('AutoGoPay',i.autogopay?.configured?'Configured':'Belum diisi')}${kv('ProdSeller',i.prodseller?.configured?'Configured':'Belum diisi')}${kv('AIVerseHub',i.aiversehub?.configured?'Configured':'Belum diisi')}</div><div class="card"><div class="card-head"><h3>Audit Log</h3></div><div class="table-wrap"><table class="table"><thead><tr><th>Waktu</th><th>Actor</th><th>Action</th><th>Detail</th><th>IP</th></tr></thead><tbody>${(audit.items||[]).map(x=>`<tr><td>${date(x.created_at)}</td><td>${esc(x.actor)}</td><td class="mono">${esc(x.action)}</td><td>${esc(x.detail)}</td><td class="mono">${esc(x.ip)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Audit kosong</td></tr>'}</tbody></table></div></div>`}
function kv(k,v){return `<div class="kv"><span>${esc(k)}</span><strong>${esc(v??'-')}</strong></div>`}
function toolbar(ph,id,buttonText,buttonId){return `<div class="toolbar"><input id="${id}" placeholder="${esc(ph)}"><span class="spacer"></span>${buttonText?`<button id="${buttonId}" class="btn primary">${esc(buttonText)}</button>`:''}</div>`}
function filterRows(rows,q,fields){q=String(q||'').toLowerCase();if(!q)return rows;return rows.filter(x=>fields.some(f=>String(x[f]||'').toLowerCase().includes(q)))}

function openModal(title,html,onSubmit){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modalForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);try{await onSubmit(Object.fromEntries(fd.entries()));$('#modal').close()}catch(err){toast(err.message,true)}};$('#modal').showModal()}
$('#modalClose').onclick=$('#modalCancel').onclick=()=>$('#modal').close();

function openTransaction(item={}){openModal(item.id?'Edit Transaksi':'Tambah Transaksi',`<div class="form-grid"><label>Order Ref<input name="order_ref" value="${esc(item.order_ref||'')}"></label><label>Telegram ID<input name="telegram_id" value="${esc(item.telegram_id||'')}"></label><label>Nama Pembeli<input name="buyer_name" value="${esc(item.buyer_name||'')}"></label><label>Nama Produk<input name="product_name" value="${esc(item.product_name||'')}"></label><label>Qty<input name="qty" type="number" min="1" value="${item.qty||1}"></label><label>Status<select name="status">${['pending','paid','completed','failed','cancelled'].map(s=>`<option ${item.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>Jumlah<input name="amount" type="number" value="${item.amount||0}"></label><label>Modal<input name="cost" type="number" value="${item.cost||0}"></label><label class="full">Catatan<textarea name="note">${esc(item.note||'')}</textarea></label></div>`,async body=>{['qty','amount','cost'].forEach(k=>body[k]=Number(body[k]||0));await api(item.id?`/api/admin/transactions/${item.id}`:'/api/admin/transactions',{method:item.id?'PATCH':'POST',body});toast('Transaksi disimpan');await loadTransactions()})}
function openProduct(item={}){openModal(item.id?'Edit Produk':'Tambah Produk',`<div class="form-grid"><label>Kode<input name="code" required value="${esc(item.code||'')}"></label><label>Nama<input name="name" required value="${esc(item.name||'')}"></label><label>Kategori<input name="category" value="${esc(item.category||'')}"></label><label>Status<select name="active"><option value="true" ${item.active!==0?'selected':''}>Aktif</option><option value="false" ${item.active===0?'selected':''}>Nonaktif</option></select></label><label>Harga<input type="number" name="price" value="${item.price||0}"></label><label>Modal<input type="number" name="cost" value="${item.cost||0}"></label><label>Stok<input type="number" name="stock" value="${item.stock||0}"></label><label class="full">Deskripsi<textarea name="description">${esc(item.description||'')}</textarea></label></div>`,async body=>{['price','cost','stock'].forEach(k=>body[k]=Number(body[k]||0));body.active=body.active==='true';await api(item.id?`/api/admin/products/${item.id}`:'/api/admin/products',{method:item.id?'PATCH':'POST',body});toast('Produk disimpan');await loadProducts()})}
function openUser(item){openModal('Edit Pengguna',`<div class="form-grid"><label>Telegram ID<input disabled value="${esc(item.telegram_id)}"></label><label>Username<input name="username" value="${esc(item.username||'')}"></label><label>Nama<input name="first_name" value="${esc(item.first_name||'')}"></label><label>Saldo<input type="number" name="balance" value="${item.balance||0}"></label><label>Status<select name="status">${['active','blocked','inactive'].map(s=>`<option ${item.status===s?'selected':''}>${s}</option>`).join('')}</select></label></div>`,async body=>{body.balance=Number(body.balance||0);await api(`/api/admin/users/${encodeURIComponent(item.telegram_id)}`,{method:'PATCH',body});toast('Pengguna diperbarui');await loadUsers()})}
function openRedeem(){openModal('Buat Redeem',`<div class="form-grid"><label>Jumlah kode<input name="count" type="number" min="1" max="100" value="1"></label><label>Tipe<select name="type"><option value="balance">balance</option><option value="credit">credit</option></select></label><label>Nilai<input name="value" type="number" value="10000"></label><label>Expired (opsional)<input name="expires_at" type="datetime-local"></label><label class="full">Kode custom (hanya jika jumlah 1)<input name="code" placeholder="Kosongkan untuk random"></label></div>`,async body=>{body.count=Number(body.count||1);body.value=Number(body.value||0);if(body.expires_at)body.expires_at=new Date(body.expires_at).toISOString();await api('/api/admin/redeem',{method:'POST',body});toast('Kode redeem dibuat');await loadRedeem()})}

function bindTableActions(){document.querySelectorAll('[data-edit-trx]').forEach(b=>b.onclick=()=>openTransaction(state.cache.transactions.find(x=>String(x.id)===b.dataset.editTrx)||{}));document.querySelectorAll('[data-del-trx]').forEach(b=>b.onclick=()=>remove(`/api/admin/transactions/${b.dataset.delTrx}`,'Hapus transaksi?',loadTransactions));
document.querySelectorAll('[data-edit-user]').forEach(b=>b.onclick=()=>openUser(state.cache.users.find(x=>String(x.telegram_id)===b.dataset.editUser)));document.querySelectorAll('[data-del-user]').forEach(b=>b.onclick=()=>remove(`/api/admin/users/${encodeURIComponent(b.dataset.delUser)}`,'Hapus pengguna?',loadUsers));
document.querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>openProduct(state.cache.products.find(x=>String(x.id)===b.dataset.editProduct)||{}));document.querySelectorAll('[data-del-product]').forEach(b=>b.onclick=()=>remove(`/api/admin/products/${b.dataset.delProduct}`,'Hapus produk?',loadProducts));
document.querySelectorAll('[data-toggle-redeem]').forEach(b=>b.onclick=async()=>{try{await api(`/api/admin/redeem/${b.dataset.toggleRedeem}`,{method:'PATCH',body:{active:b.dataset.active!=='1'}});loadRedeem()}catch(e){toast(e.message,true)}});document.querySelectorAll('[data-del-redeem]').forEach(b=>b.onclick=()=>remove(`/api/admin/redeem/${b.dataset.delRedeem}`,'Hapus redeem?',loadRedeem));
document.querySelectorAll('[data-download-backup]').forEach(b=>b.onclick=()=>downloadBackup(b.dataset.downloadBackup));document.querySelectorAll('[data-del-backup]').forEach(b=>b.onclick=()=>remove(`/api/admin/backups?name=${encodeURIComponent(b.dataset.delBackup)}`,'Hapus backup?',loadBackups));}
async function remove(path,msg,reload){if(!confirm(msg))return;try{await api(path,{method:'DELETE'});toast('Berhasil dihapus');await reload()}catch(e){toast(e.message,true)}}
async function downloadBackup(name){try{const res=await api(`/api/admin/backups/download?name=${encodeURIComponent(name)}`,{raw:true});const blob=await res.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){toast(e.message,true)}}

(async function boot(){if(!state.token)return showLogin();try{await api('/api/admin/me');showApp();await navigate('overview')}catch{logout(false)}})();
